routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/contact', function () {
    return view('contact');
});
Route::get('/elements', function () {
    return view('elements');
});
Route::get('/services', function () {
    return view('services');
});


Route::group(['as' => 'frontend', 'namespace' => 'Frontend'], function() {
  Route::get('/', 'HomeController@index');
  Route::get('/about', 'AboutController@index');

  Route::get('/pages/{slug}', 'PageController@category');
  Route::get('/page/{slug}', 'PageController@show');

  // Route::get('/contacts', 'ContactController@index');

});



Auth::routes();

// Social login
Route::get('/login/{social}','Auth\LoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/login/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');

//Image resize & crop on view:  http://image.intervention.io/
Route::get('/resize/{w}/{h}',function($w=null, $h=null){
  $img = Illuminate\Support\Facades\Input::get("img");
  return \Image::make(public_path(urldecode($img)))->fit($w, $h, function ($constraint) {
      $constraint->upsize();
  })->response('jpg');
 });

// Admin
Route::group(['as' => 'admin.', 'middleware' => 'roles','roles' =>['admin', 'sadmin'], 'namespace' => 'Admin', 'prefix' => 'admin'], function() {

    App::setLocale('ua');

    Route::put('ajax/status', ['as' => 'ajax.status', 'uses' => 'AjaxController@status']);
    Route::put('ajax/reorder', ['as' => 'ajax.reorder', 'uses' => 'AjaxController@reorder']);

    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::resource('user', 'UserController');
    Route::resource('page-category', 'PageCategoryController');
    Route::resource('page', 'PageController');
    Route::resource('department', 'DepartmentController');
    Route::resource('doctor', 'DoctorController');
    Route::resource('faq', 'FaqController');
});

resources/views/admin/page/category_create.blade.php
@extends('admin.layout')

@section('content')
<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.category')</h3>
  </div>

  <div class="card-body">

    {!! Form::open(['route' => ['admin.page-category.store'], 'method' => 'POST']) !!}
      @include('admin.page.category_form')
    {!! Form::close() !!}

  </div>
</div>

@endsection

resources/views/admin/page/category_edit.blade.php
@extends('admin.layout')

@section('content')
<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.category')</h3>
  </div>

  <div class="card-body">

    {!! Form::open(['route' => ['admin.page-category.update', $category->id], 'method' => 'PUT']) !!}
      @include('admin.page.category_form')
    {!! Form::close() !!}

  </div>
</div>

@endsection

resources/views/admin/page/category_form.blade.php
<div class="form-group row">
  <label for="title" class="col-sm-2 col-form-label">@lang('message.title')</label>
  <div class="col-sm-10">
    {!! Form::text('title', $category->title, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group row">
  <label for="image" class="col-sm-2 col-form-label">@lang('message.image')</label>
  <div class="col-sm-10">
    <img id="holder" style="margin-top:15px;max-height:100px;" src="{{ $category->image }}">
    <a id="lfm" data-input="thumbnail" data-preview="holder" class="lfm btn btn-primary">
      <i class="icon icon-picture"></i> @lang('message.select')
    </a>
    <a id="delete-image" class="btn btn-danger {{($category->image) ? '' : 'hidden'}}">
      <i class="icon icon-trash"></i> @lang('message.delete')
    </a>
  </div>
  <input id="thumbnail" class="form-control" type="hidden" name="image" value="{{ $category->image }}">
</div>

<div class="form-group row">
  <label for="description" class="col-sm-2 col-form-label">@lang('message.description')</label>
  <div class="col-sm-10">
    {!! Form::textarea('description', $category->description, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="toggle-switch" data-ts-color="primary">
  {!! Form::hidden('published', 0) !!}
  <label for="published" class="ts-label">@lang('message.published')</label>
  {!! Form::checkbox('published', 1, $category->published, ['hidden' => 'hidden', 'id' => 'published']) !!}
  <label for="published" class="ts-helper"></label>
</div>

<hr>

<div class="form-group row">
  <label for="slug" class="col-sm-2 col-form-label">@lang('message.slug')</label>
  <div class="col-sm-10">
    {!! Form::text('slug', $category->slug, ['class' => 'form-control', 'placeholder' => Lang::get('message.gen_auto')]) !!}
  </div>
</div>

<button type="submit" class="btn btn-success">
  <i class="fa fa-download"></i> &nbsp; @lang('message.save')
</button>

resources/views/admin/page/category_index.blade.php
@extends('admin.layout')

@section('content')

<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.categories')</h3>
    <div>
      <a href="{{ route('admin.page-category.create') }}" class="btn btn-light"><i class="fa fa-plus-square-o"></i> @lang('message.create')</a>
    </div>
  </div>

  <div class="card-body" style="position: relative;">
    <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">actions</th>
            <th scope="col">@lang('message.title')</th>
            <th scope="col">@lang('message.image')</th>
            <th scope="col">@lang('message.description')</th>
            <th scope="col">@lang('message.published')</th>
          </tr>
        </thead>
        <tbody>

          @foreach($categories as $item)
          <tr data-id="{{$item->id}}">
            <th scope="row">{{$item->id}}</th>
            <td>
              <a href="{{ route('admin.page-category.edit', $item->id) }}" title="Edit"><i class="fa fa-edit"></i></a>
              @if($item->id > 1)
              &nbsp;&nbsp;&nbsp;
              <a href="{{ route('admin.page-category.destroy', $item->id) }}" title="Delete" class="delete-item"><i class="fa fa-trash-o"></i></a>
              @endif
            </td>
            <td>{{$item->title}}</td>
            <td><img src="/resize/75/30/?img={{urlencode($item->image)}}"></td>
            <td>{!! $item->description !!}</td>
            <td>
              <a href="{{route('admin.ajax.status', ['id' => $item->id, 'model' => 'PageCategory', 'field' => 'published'])}}" class="status fa fa-{{$item->published ? 'check-circle' : 'times-circle'}}"></a>
            </td>
          </tr>
          @endforeach

        </tbody>
      </table>
    </div>
  </div>

</div>

@endsection

resources/views/admin/page/create.blade.php
@extends('admin.layout')

@section('content')
<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.page')</h3>
  </div>

  <div class="card-body">

    {!! Form::open(['route' => ['admin.page.store'], 'method' => 'POST']) !!}
      @include('admin.page.form')
    {!! Form::close() !!}

  </div>
</div>

@endsection

resources/views/admin/page/edit.blade.php
@extends('admin.layout')

@section('content')
<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.page')</h3>
  </div>

  <div class="card-body">

    {!! Form::open(['route' => ['admin.page.update', $page->id], 'method' => 'PUT']) !!}
      @include('admin.page.form')
    {!! Form::close() !!}

  </div>
</div>

@endsection

resources/views/admin/page/form.blade.php
<div class="form-group row">
  <label for="category" class="col-sm-2 col-form-label">@lang('message.category')</label>
  <div class="col-sm-10">
    {!! Form::select('category_id', $page->categories(), $page->category_id, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group row">
  <label for="title" class="col-sm-2 col-form-label">@lang('message.title')</label>
  <div class="col-sm-10">
    {!! Form::text('title', $page->title, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group row">
  <label for="image" class="col-sm-2 col-form-label">@lang('message.image')</label>
  <div class="col-sm-10">
    <img id="holder" style="margin-top:15px;max-height:100px;" src="{{ $page->image }}">
    <a id="lfm" data-input="thumbnail" data-preview="holder" class="lfm btn btn-primary">
      <i class="icon icon-picture"></i> @lang('message.select')
    </a>
    <a id="delete-image" class="btn btn-danger {{($page->image) ? '' : 'hidden'}}">
      <i class="icon icon-trash"></i> @lang('message.delete')
    </a>
  </div>
  <input id="thumbnail" class="form-control" type="hidden" name="image" value="{{ $page->image }}">
</div>

<div class="form-group row">
  <label for="preview" class="col-sm-2 col-form-label">@lang('message.preview')</label>
  <div class="col-sm-10">
    {!! Form::textarea('preview', $page->preview, ['class' => 'form-control', 'rows' => '2']) !!}
  </div>
</div>

<div class="form-group row">
  <label for="content" class="col-sm-2 col-form-label">@lang('message.content')</label>
  <div class="col-sm-10">
    {!! Form::textarea('content', $page->content, ['class' => 'form-control']) !!}
  </div>
</div>


<div class="toggle-switch" data-ts-color="primary">
  {!! Form::hidden('published', 0) !!}
  <label for="published" class="ts-label">@lang('message.published')</label>
  {!! Form::checkbox('published', 1, $page->published, ['id' => 'published']) !!}
  <label for="published" class="ts-helper"></label>
</div>

<hr>

<div class="toggle-switch" data-ts-color="primary">
  {!! Form::hidden('show_on_main', 0) !!}
  <label for="show_on_main" class="ts-label">@lang('message.show_on_main')</label>
  {!! Form::checkbox('show_on_main', 1, $page->show_on_main, ['id' => 'show_on_main']) !!}
  <label for="show_on_main" class="ts-helper"></label>
</div>

<hr>

<div class="form-group row">
  <label for="slug" class="col-sm-2 col-form-label">@lang('message.slug')</label>
  <div class="col-sm-10">
    {!! Form::text('slug', $page->slug, ['class' => 'form-control', 'placeholder' => Lang::get('message.gen_auto')]) !!}
  </div>
</div>

<button type="submit" class="btn btn-success">
  <i class="fa fa-download"></i> &nbsp; @lang('message.save')
</button>

resources/views/admin/page/index.blade.php
@extends('admin.layout')

@section('content')

<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.page')</h3>
    <div>
      <a href="{{ route('admin.page.create') }}" class="btn btn-light"><i class="fa fa-plus-square-o"></i> @lang('message.create')</a>

      <div class="dropdown float-right">
        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Категорія
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          @foreach($categories as $id => $title)
            <a class="dropdown-item" href="{{ route('admin.page.index') }}?category={{$id}}">{{$title}}</a>
          @endforeach
        </div>
      </div>

    </div>
  </div>

  <div class="card-body" style="position: relative;">
    <div class="table-responsive">
      <table class="table text-center sorted_table" model="Page">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">actions</th>
            <th scope="col">@lang('message.category')</th>
            <th scope="col">@lang('message.title')</th>
            <th scope="col">@lang('message.image')</th>
            <th scope="col">@lang('message.preview')</th>
            <th scope="col">@lang('message.published')</th>
          </tr>
        </thead>
        <tbody>

          @foreach($page as $item)
          <tr data-id="{{$item->id}}">
            <th scope="row">{{$item->id}}</th>
            <td>
              <a href="{{ route('admin.page.edit', $item->id) }}" title="Edit"><i class="fa fa-edit"></i></a>
              &nbsp;&nbsp;&nbsp;
              <a href="{{ route('admin.page.destroy', $item->id) }}" title="Delete" class="delete-item"><i class="fa fa-trash-o"></i></a>
            </td>
            <td>{{$item->category->title}}</td>
            <td>{{$item->title}}</td>
            <td><img src="/resize/50/40/?img={{urlencode($item->image)}}"></td>
            <td>{!! $item->preview !!}</td>
            <td>
              <a href="{{route('admin.ajax.status', ['id' => $item->id, 'model' => 'Page', 'field' => 'published'])}}" class="status fa fa-{{$item->published ? 'check-circle' : 'times-circle'}}"></a>
            </td>
          </tr>
          @endforeach

        </tbody>
      </table>
    </div>
  </div>

</div>

@endsection