routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/contact', function () {
    return view('contact');
});
Route::get('/elements', function () {
    return view('elements');
});
Route::get('/services', function () {
    return view('services');
});


Route::group(['as' => 'frontend', 'namespace' => 'Frontend'], function() {
  Route::get('/', 'HomeController@index');
  Route::get('/about', 'AboutController@index');

  Route::get('/pages/{slug}', 'PageController@category');
  Route::get('/page/{slug}', 'PageController@show');

  // Route::get('/contacts', 'ContactController@index');

});



Auth::routes();

// Social login
Route::get('/login/{social}','Auth\LoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/login/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');

//Image resize & crop on view:  http://image.intervention.io/
Route::get('/resize/{w}/{h}',function($w=null, $h=null){
  $img = Illuminate\Support\Facades\Input::get("img");
  return \Image::make(public_path(urldecode($img)))->fit($w, $h, function ($constraint) {
      $constraint->upsize();
  })->response('jpg');
 });

// Admin
Route::group(['as' => 'admin.', 'middleware' => 'roles','roles' =>['admin', 'sadmin'], 'namespace' => 'Admin', 'prefix' => 'admin'], function() {

    App::setLocale('ua');

    Route::put('ajax/status', ['as' => 'ajax.status', 'uses' => 'AjaxController@status']);
    Route::put('ajax/reorder', ['as' => 'ajax.reorder', 'uses' => 'AjaxController@reorder']);

    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::resource('user', 'UserController');
    Route::resource('page-category', 'PageCategoryController');
    Route::resource('page', 'PageController');
    Route::resource('department', 'DepartmentController');
    Route::resource('doctor', 'DoctorController');
    Route::resource('faq', 'FaqController');
});

app/Http/Controllers/Admin/DepartmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Department;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;

class DepartmentController extends Controller
{
    public function index()
    {
        return view('admin.department.index', [
            'page' => Department::orderBy('order')->get()
        ]);
    }

    public function create()
    {
        return view('admin.department.create', ['page' => new Department]);
    }

    public function store(Request $request, Department $department)
    {
        $request->validate([
            'title' => 'required',
        ]);

        $department = $department->create($request->all());

        return redirect()->route('admin.department.index')->with('success', 'Item created');
    }

    public function show(Department $department)
    {
        return view('admin.department.show', ['page' => $department]);
    }

    public function edit(Department $department)
    {
        return view('admin.department.edit', ['page' => $department]);
    }

    public function update(Request $request, Department $department)
    {
        $request->validate([
            'title' => 'required',
        ]);

        $data = $request->all();

        $department->update($data);

        if (array_key_exists('redirect', $data)) return redirect()->route('admin.dashboard')->with('success', 'Item updated');

        return redirect()->route('admin.department.index')->with('success', 'Item updated');
    }

    public function destroy(Department $department)
    {
        $department->delete();

        return 'success';
    }
}

resources/views/admin/department/create.blade.php
@extends('admin.layout')

@section('content')
<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.department')</h3>
  </div>

  <div class="card-body">

    {!! Form::open(['route' => ['admin.department.store'], 'method' => 'POST']) !!}
      @include('admin.department.form')
    {!! Form::close() !!}

  </div>
</div>

@endsection

resources/views/admin/department/edit.blade.php
@extends('admin.layout')

@section('content')
<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.department')</h3>
  </div>

  <div class="card-body">

    {!! Form::open(['route' => ['admin.department.update', $page->id], 'method' => 'PUT']) !!}
      @include('admin.department.form')
    {!! Form::close() !!}

  </div>
</div>

@endsection

resources/views/admin/department/form.blade.php
<div class="form-group row">
  <label for="title" class="col-sm-2 col-form-label">@lang('message.title')</label>
  <div class="col-sm-10">
    {!! Form::text('title', $page->title, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group row">
  <label for="image" class="col-sm-2 col-form-label">@lang('message.image')</label>
  <div class="col-sm-10">
    <img id="holder" style="margin-top:15px;max-height:100px;" src="{{ $page->image }}">
    <a id="lfm" data-input="thumbnail" data-preview="holder" class="lfm btn btn-primary">
      <i class="icon icon-picture"></i> @lang('message.select')
    </a>
    <a id="delete-image" class="btn btn-danger {{($page->image) ? '' : 'hidden'}}">
      <i class="icon icon-trash"></i> @lang('message.delete')
    </a>
  </div>
  <input id="thumbnail" class="form-control" type="hidden" name="image" value="{{ $page->image }}">
</div>

<div class="form-group row">
  <label for="text" class="col-sm-2 col-form-label">@lang('message.description')</label>
  <div class="col-sm-10">
    {!! Form::textarea('text', $page->text, ['class' => 'form-control', 'rows' => '2']) !!}
  </div>
</div>

<div class="toggle-switch" data-ts-color="primary">
  {!! Form::hidden('published', 0) !!}
  <label for="published" class="ts-label">@lang('message.published')</label>
  {!! Form::checkbox('published', 1, $page->published, ['id' => 'published']) !!}
  <label for="published" class="ts-helper"></label>
</div>

<hr>


<button type="submit" class="btn btn-success">
  <i class="fa fa-download"></i> &nbsp; @lang('message.save')
</button>

resources/views/admin/department/index.blade.php
@extends('admin.layout')

@section('content')

<div class="card">
  <div class="card-header bg-light">
    <h3>@lang('message.department')</h3>
    <div>
      <a href="{{ route('admin.department.create') }}" class="btn btn-light"><i class="fa fa-plus-square-o"></i> @lang('message.create')</a>
    </div>
  </div>

  <div class="card-body" style="position: relative;">
    <div class="table-responsive">
      <table class="table text-center sorted_table" model="Department">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">actions</th>
            <th scope="col">@lang('message.title')</th>
            <th scope="col">@lang('message.image')</th>
            <th scope="col">@lang('message.published')</th>
          </tr>
        </thead>
        <tbody>

          @foreach($page as $item)
          <tr data-id="{{$item->id}}">
            <th scope="row">{{$item->id}}</th>
            <td>
              <a href="{{ route('admin.department.edit', $item->id) }}" title="Edit"><i class="fa fa-edit"></i></a>
              &nbsp;&nbsp;&nbsp;
              <a href="{{ route('admin.department.destroy', $item->id) }}" title="Delete" class="delete-item"><i class="fa fa-trash-o"></i></a>
            </td>
            <td>{{$item->title}}</td>
            <td><img src="/resize/50/40/?img={{urlencode($item->image)}}"></td>
            <td>
              <a href="{{route('admin.ajax.status', ['id' => $item->id, 'model' => 'Page', 'field' => 'published'])}}" class="status fa fa-{{$item->published ? 'check-circle' : 'times-circle'}}"></a>
            </td>
          </tr>
          @endforeach

        </tbody>
      </table>
    </div>
  </div>

</div>

@endsection